export const projectsData = [
    {
        id: "breakout", name: "Breakout Blast", description: "Arcade classic brick-breaker with power-ups and vibrant effects.",
        preview: `<canvas id="breakout-game" width="600" height="450"></canvas>`, initKey: "initBreakoutGame",
        category: "arcade", icon: "fa-th", iconColor: "#e74c3c",
        instructions: "Mouse to move paddle. Break all bricks. Catch falling power-ups!",
    },
    {
        id: "snake", name: "Hyper Snake", description: "Timeless snake game with faster speeds and a modern neon look.",
        preview: `<canvas id="snake-game" width="400" height="400"></canvas>`, initKey: "initSnakeGame",
        category: "retro", icon: "fa-wave-square", iconColor: "#2ecc71",
        instructions: "Arrow keys to move. Eat food (red squares) to grow. Avoid walls and yourself.",
    },
    // ... (all other 28 project objects, similar structure with initKey)
    {
        id: "tetris", name: "Tetris Dimensions", description: "Falling block puzzle game. Clear lines, score high!",
        preview: `<canvas id="tetris-game" width="300" height="600"></canvas>`, initKey: "initTetrisGame",
        category: "puzzle", icon: "fa-shapes", iconColor: "#3498db",
        instructions: "Arrows: Left/Right to move, Down to soft drop, Up to rotate. Space for hard drop. Clear lines.",
    },
    {
        id: "pong", name: "Quantum Pong", description: "The original paddle game with a futuristic twist.",
        preview: `<canvas id="pong-game" width="600" height="400"></canvas>`, initKey: "initPongGame",
        category: "retro", icon: "fa-table-tennis", iconColor: "#f1c40f",
        instructions: "Player 1 (Left): W/S keys. Player 2 (Right): Up/Down Arrows. Score points!",
    },
    {
        id: "spaceinvaders", name: "Galaxy Invaders", description: "Defend Earth from descending alien hordes!",
        preview: `<canvas id="spaceinvaders-game" width="500" height="450"></canvas>`, initKey: "initSpaceInvadersGame",
        category: "action", icon: "fa-space-shuttle", iconColor: "#9b59b6",
        instructions: "Left/Right Arrows to move. Spacebar to shoot. Destroy all invaders.",
    },
    {
        id: "asteroids", name: "Asteroid Belt", description: "Navigate space, destroy asteroids and UFOs.",
        preview: `<canvas id="asteroids-game" width="500" height="500"></canvas>`, initKey: "initAsteroidsGame",
        category: "action", icon: "fa-meteor", iconColor: "#7f8c8d",
        instructions: "Arrows: Left/Right to rotate, Up to thrust. Spacebar to shoot. Avoid collisions.",
    },
    {
        id: "pacman", name: "Dot Muncher", description: "Navigate the maze, eat dots, avoid ghosts!",
        preview: `<canvas id="pacman-game" width="448" height="496"></canvas>`, initKey: "initPacmanGame",
        category: "arcade", icon: "fa-ghost", iconColor: "#f39c12",
        instructions: "Arrow keys to move. Eat all dots to win. Avoid ghosts. Eat power pellets (large dots) to eat ghosts.",
    },
    {
        id: "frogger", name: "Road Hopper", description: "Help the frog cross the busy road and river.",
        preview: `<canvas id="frogger-game" width="400" height="480"></canvas>`, initKey: "initFroggerGame",
        category: "arcade", icon: "fa-frog", iconColor: "#1abc9c",
        instructions: "Arrow keys to move. Reach the empty lilypads at the top. Avoid cars and water hazards.",
    },
    {
        id: "minesweeper", name: "Mine Sweeper Pro", description: "Classic logic puzzle. Flag the mines, clear the board.",
        preview: `<div id="minesweeper-game" style="padding: 1vh;"></div>`, initKey: "initMinesweeperGame",
        category: "puzzle", icon: "fa-bomb", iconColor: "#34495e",
        instructions: "Left-click to reveal square. Right-click (or Ctrl+click) to flag mine. Numbers show adjacent mines.",
    },
    {
        id: "connect4", name: "Connect Four", description: "Drop discs, connect four in a row vertically, horizontally, or diagonally.",
        preview: `<canvas id="connect4-game" width="420" height="360"></canvas>`, initKey: "initConnect4Game",
        category: "puzzle", icon: "fa-grip-horizontal", iconColor: "#e74c3c",
        instructions: "Click on a column to drop your disc (Red). Get four in a row before the AI (Yellow).",
    },
    {
        id: "flappybird", name: "Flappy Pipe", description: "Tap to flap, navigate through the pipes.",
        preview: `<canvas id="flappybird-game" width="300" height="500"></canvas>`, initKey: "initFlappyBirdGame",
        category: "arcade", icon: "fa-kiwi-bird", iconColor: "#f1c40f",
        instructions: "Spacebar or Click to flap upwards. Avoid pipes and the ground.",
    },
    {
        id: "doodlejump", name: "Doodle Jumper", description: "Jump ever higher on platforms, avoid falling.",
        preview: `<canvas id="doodlejump-game" width="400" height="600"></canvas>`, initKey: "initDoodleJumpGame",
        category: "arcade", icon: "fa-angle-double-up", iconColor: "#2ecc71",
        instructions: "Left/Right Arrows to move horizontally. Bounce automatically on platforms.",
    },
    {
        id: "memory", name: "Memory Match", description: "Flip cards and find matching pairs.",
        preview: `<div id="memory-game" style="padding: 2vh; display: grid; gap: 1vh;"></div>`, initKey: "initMemoryGame",
        category: "puzzle", icon: "fa-brain", iconColor: "#9b59b6",
        instructions: "Click cards to reveal them. Find all matching pairs.",
    },
    {
        id: "clicker", name: "Idle Clicker", description: "Click the button, earn points, buy upgrades.",
        preview: `<div id="clicker-game" style="padding: 2vh; text-align: center;"></div>`, initKey: "initClickerGame",
        category: "casual", icon: "fa-mouse-pointer", iconColor: "#3498db",
        instructions: "Click the main button to earn points. Buy upgrades to increase points per click or auto-click.",
    },
    {
        id: "maze", name: "Labyrinth Run", description: "Find your way through the maze to the exit.",
        preview: `<canvas id="maze-game" width="400" height="400"></canvas>`, initKey: "initMazeGame",
        category: "puzzle", icon: "fa-project-diagram", iconColor: "#7f8c8d",
        instructions: "Arrow keys to move the player (blue square) to the exit (green square).",
    },
    {
        id: "typing", name: "Typing Speed Test", description: "Test and improve your typing speed.",
        preview: `<div id="typing-game" style="padding: 2vh;"></div>`, initKey: "initTypingGame",
        category: "casual", icon: "fa-keyboard", iconColor: "#1abc9c",
        instructions: "Type the displayed words accurately. Results shown at the end.",
    },
    {
        id: "wordsearch", name: "Word Search", description: "Find the hidden words in the grid.",
        preview: `<div id="wordsearch-game" style="padding: 1vh;"></div>`, initKey: "initWordSearchGame",
        category: "puzzle", icon: "fa-search", iconColor: "#e74c3c",
        instructions: "Click and drag to highlight words found in the list. Words can be horizontal, vertical, or diagonal.",
    },
    {
        id: "hangman", name: "Hangman Classic", description: "Guess the letters to find the hidden word.",
        preview: `<div id="hangman-game" style="padding: 2vh;"></div>`, initKey: "initHangmanGame",
        category: "puzzle", icon: "fa-user-secret", iconColor: "#34495e",
        instructions: "Click letters to guess. Too many wrong guesses and the game is over!",
    },
    {
        id: "simonsays", name: "Simon Says", description: "Repeat the sequence of colors and sounds.",
        preview: `<div id="simonsays-game" style="padding: 2vh; display: flex; justify-content: center;"></div>`, initKey: "initSimonSaysGame",
        category: "casual", icon: "fa-palette", iconColor: "#f39c12",
        instructions: "Watch the sequence, then click the buttons in the same order.",
    },
    {
        id: "tictactoe", name: "Tic Tac Toe AI", description: "Classic Tic Tac Toe against a simple AI.",
        preview: `<div id="tictactoe-game" style="padding: 2vh;"></div>`, initKey: "initTicTacToeGame",
        category: "puzzle", icon: "fa-times", iconColor: "#2ecc71",
        instructions: "Click on an empty square to place your 'X'. Try to get 3 in a row before the AI ('O').",
    },
    {
        id: "arkanoid", name: "Arkanoid Lite", description: "Breakout variant with moving bricks (simple).",
        preview: `<canvas id="arkanoid-game" width="600" height="450"></canvas>`, initKey: "initArkanoidGame",
        category: "arcade", icon: "fa-th-large", iconColor: "#e74c3c",
        instructions: "Mouse to move paddle. Similar to Breakout, but some bricks might move.",
    },
    {
        id: "platformer", name: "Simple Platformer", description: "Basic jump and run platformer.",
        preview: `<canvas id="platformer-game" width="600" height="400"></canvas>`, initKey: "initPlatformerGame",
        category: "action", icon: "fa-running", iconColor: "#3498db",
        instructions: "Left/Right Arrows to move. Up Arrow or Space to jump. Reach the goal.",
    },
    {
        id: "shooter", name: "Top-Down Shooter", description: "Simple top-down shooting gallery.",
        preview: `<canvas id="shooter-game" width="500" height="500"></canvas>`, initKey: "initShooterGame",
        category: "action", icon: "fa-crosshairs", iconColor: "#9b59b6",
        instructions: "WASD or Arrows to move. Mouse click to shoot targets.",
    },
    {
        id: "match3", name: "Match-3 Gems", description: "Swap adjacent gems to match 3 or more.",
        preview: `<canvas id="match3-game" width="400" height="400"></canvas>`, initKey: "initMatch3Game",
        category: "puzzle", icon: "fa-gem", iconColor: "#1abc9c",
        instructions: "Click and drag a gem to swap with an adjacent one. Match 3 or more of the same color.",
    },
    {
        id: "rhythm", name: "Rhythm Tap", description: "Tap the notes as they reach the target line.",
        preview: `<canvas id="rhythm-game" width="400" height="500"></canvas>`, initKey: "initRhythmGame",
        category: "casual", icon: "fa-music", iconColor: "#f1c40f",
        instructions: "Press the corresponding keys (e.g., D, F, J, K) as notes hit the line.",
    },
    {
        id: "drawing", name: "Simple Draw Pad", description: "A basic canvas for drawing.",
        preview: `<canvas id="drawing-game" width="500" height="400" style="background: #fff; cursor: crosshair;"></canvas>`, initKey: "initDrawingGame",
        category: "casual", icon: "fa-paint-brush", iconColor: "#e74c3c",
        instructions: "Click and drag to draw. Controls for color/clear might be added.",
    },
    {
        id: "physics", name: "Physics Balls", description: "Simple physics simulation with bouncing balls.",
        preview: `<canvas id="physics-game" width="500" height="400"></canvas>`, initKey: "initPhysicsGame",
        category: "casual", icon: "fa-atom", iconColor: "#3498db",
        instructions: "Watch the balls bounce around. Click to add more balls.",
    },
    {
        id: "cardgame", name: "Simple Card Game", description: "Basic High-Low card guessing game.",
        preview: `<div id="cardgame-game" style="padding: 2vh;"></div>`, initKey: "initCardGame",
        category: "casual", icon: "fa-heart", iconColor: "#e74c3c",
        instructions: "Guess if the next card drawn will be higher or lower than the current card.",
    },
    {
        id: "adventure", name: "Text Adventure Snippet", description: "A tiny example of a text-based adventure.",
        preview: `<div id="adventure-game" style="padding: 2vh; height: 30vh; overflow-y: auto; background: #000; color: #0f0; font-family: monospace;"></div>`, initKey: "initAdventureGame",
        category: "retro", icon: "fa-terminal", iconColor: "#2ecc71",
        instructions: "Type commands like 'look', 'north', 'take key' etc. (Very basic).",
    },
    {
        id: "sudoku", name: "Sudoku Mini", description: "A very simple Sudoku puzzle generator/solver.",
        preview: `<div id="sudoku-game" style="padding: 1vh;"></div>`, initKey: "initSudokuGame",
        category: "puzzle", icon: "fa-border-all", iconColor: "#34495e",
        instructions: "Fill the grid so each row, column, and 3x3 box contains digits 1-9. (Basic implementation)",
    },
];